/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "nfbwsklzpqfsrpcgdzjd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mYndza2x6cHFmc3JwY2dkempkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIzMjE2MjIsImV4cCI6MjA3Nzg5NzYyMn0.HPh5ZWRWiH_6o9xSDP-YxI3bU7ymscnhI-UzhMNHQe4"